<a href="https://colab.research.google.com/github/wambugudan/Data-Science-Projects/blob/main/COVID_19_Vaccination_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Name: Daniel Wambugu Maina

# Reg. No: 22/01973

# Course: MDA 5105 - Principles of Data Science

# Assignment 1

## Importing all the required Libraries

In [ ]:
#Importing all the required Libraries

import pandas as pd
import numpy as nm
from sklearn import preprocessing
from sklearn.preprocessing import Normalizer
from sklearn.preprocessing import Binarizer
from sklearn.decomposition import PCA
from numpy import set_printoptions
from IPython.display import display


## Task 1: Extarcting Data from the data source

In [ ]:
# Reading data from source file and printing it in the output

path = "C:\\pydatafile\\country_vaccinations.csv"
df = pd.read_csv(path)

print("\n Pringting raw data: \n\n", display(df))

location        date             vaccine  total_vaccinations
0           Argentina  2020-12-29             Moderna                   2
1           Argentina  2020-12-29  Oxford/AstraZeneca                   3
2           Argentina  2020-12-29   Sinopharm/Beijing                   1
3           Argentina  2020-12-29           Sputnik V               20481
4           Argentina  2020-12-30             Moderna                   2
...               ...         ...                 ...                 ...
35618  European Union  2022-03-29  Oxford/AstraZeneca            67403106
35619  European Union  2022-03-29     Pfizer/BioNTech           600519998
35620  European Union  2022-03-29   Sinopharm/Beijing             2301516
35621  European Union  2022-03-29             Sinovac                1809
35622  European Union  2022-03-29           Sputnik V             1845103

[35623 rows x 4 columns]


 Pringting raw data: 

 None


## Task 2: Labelling Data

In [ ]:
# Performing data Labelling & pringting the output

Encoder = preprocessing.LabelEncoder()
Encoded_Dataframe = df.apply(Encoder.fit_transform)

print("\n Pringting Encoded data: \n", display(Encoded_Dataframe))

location  date  vaccine  total_vaccinations
0             0    16        3                   2
1             0    16        5                   3
2             0    16        7                   1
3             0    16        9                1543
4             0    17        3                   2
...         ...   ...      ...                 ...
35618        11   471        5               27361
35619        11   471        6               29209
35620        11   471        7               15010
35621        11   471        8                 614
35622        11   471        9               13947

[35623 rows x 4 columns]


 Pringting Encoded data: 
 None


## Task 3: Data Splitting

In [ ]:
# Seperating Numeric Data from attributes labels

Numeric_Data = Encoded_Dataframe.values
print("\n Printing the data without attributes labels: \n\n", Numeric_Data)


 Printing the data without attributes labels: 

 [[    0    16     3     2]
 [    0    16     5     3]
 [    0    16     7     1]
 ...
 [   11   471     7 15010]
 [   11   471     8   614]
 [   11   471     9 13947]]


In [ ]:
# Splitting Data
x_attributes = Numeric_Data[:,:-1]
y_attributes = Numeric_Data[:,-1]

print("\n Splitted Input Attributes sample: \n\n", x_attributes, "\n\n Splitted Output Attributes sample: \n", y_attributes)


 Splitted Input Attributes sample: 

 [[  0  16   3]
 [  0  16   5]
 [  0  16   7]
 ...
 [ 11 471   7]
 [ 11 471   8]
 [ 11 471   9]] 

 Splitted Output Attributes sample: 
 [    2     3     1 ... 15010   614 13947]


## Task 4: Normalizing Data

In [ ]:
# Normalizing data and printing the output

normalized_x_attributes = preprocessing.normalize(x_attributes)
normalized_y_attributes = preprocessing.normalize(x_attributes)
print("\n Normalized Input Attributes: \n\n", normalized_x_attributes)


 Normalized Input Attributes: 

 [[0.         0.98287219 0.18428854]
 [0.         0.95447998 0.29827499]
 [0.         0.91615733 0.40081883]
 ...
 [0.02334562 0.99961706 0.0148563 ]
 [0.02334483 0.9995833  0.01697806]
 [0.02334394 0.99954503 0.01909959]]


## Task 5: Standardizing Data

In [ ]:
# Standardizing Data & Printing the output

standardized_x_attributes = preprocessing.scale(x_attributes)
print("\n Standardized input attributes: \n\n", standardized_x_attributes)


 Standardized input attributes: 

 [[-1.48289869 -1.93307583 -0.7622446 ]
 [-1.48289869 -1.93307583  0.20025081]
 [-1.48289869 -1.93307583  1.16274622]
 ...
 [-0.65222316  1.72215363  1.16274622]
 [-0.65222316  1.72215363  1.64399393]
 [-0.65222316  1.72215363  2.12524163]]


## Task 6: Binarizing Data

In [ ]:
#Binarizing Data

Binarizer = Binarizer(threshold = 1.0).fit(x_attributes)
Binarized_x_attributes = Binarizer.transform(x_attributes)
print("\n Binarized output: \n\n", Binarized_x_attributes)


 Binarized output: 

 [[0 1 1]
 [0 1 1]
 [0 1 1]
 ...
 [1 1 1]
 [1 1 1]
 [1 1 1]]


## Task 7: Compressing Data

In [ ]:
# Decomposing the number of attributes to two and printing the output

pca = PCA(n_components = 2)
pca.fit(x_attributes)
Decomposed_x_attributes = pca.transform(x_attributes)

print("\n Decomposed Input Attributes: \n\n", Decomposed_x_attributes)


 Decomposed Input Attributes: 

 [[ 240.71056273  -18.56203882]
 [ 240.71234426  -18.57518912]
 [ 240.7141258   -18.58833941]
 ...
 [-214.32982658   -9.60025338]
 [-214.32893582   -9.60682853]
 [-214.32804505   -9.61340368]]
